version: '3'
services:
  app:
    image: habiebzain/laravel-app:prod
    container_name: app
    hostname: app_server
    restart: unless-stopped
    tty: true
    env_file: .env
    environment:
      - TZ=Asia/Jakarta
    depends_on:
      - cache
    networks:
      - laravel-prod

  web_server:
    image: habiebzain/webserver:prod
    container_name: web_server
    hostname: web_server
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "8002:80"
    depends_on:
      - app
    networks:
      - laravel-prod

  cache:
    image: redis:alpine
    container_name: cache
    restart: unless-stopped
    networks:
      - laravel-prod

#Docker Networks
networks:
  laravel-prod:
    driver: bridge
